language: php
git:
  depth: 5
  quiet: true
before_script:
  - composer install
  - cd tests
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
