language: php
git:
  depth: 5
  quiet: true
before_script:
  - composer install
  - cd tests
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
